# build.yml
on:
  release:
    types: [released]

name: Build and Deploy
jobs:
  deploy_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - name: Login to DockerHub Registry
      #   run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      # - name: Get the version
      #   id: vars
      #   run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      # - name: Build the tagged Docker image
      #   run: docker build . --file Dockerfile --tag majrlzr/bmicalc:${{steps.vars.outputs.tag}}
      # - name: Push the tagged Docker image
      #   run: docker push majrlzr/bmicalc:${{steps.vars.outputs.tag}}
      # - name: Build the latest Docker image
      #   run: docker build . --file Dockerfile --tag majrlzr/bmicalc:latest
      # - name: Push the latest Docker image
      #   run: docker push majrlzr/bmicalc:latest
      - name: Deploy Containers
        run: |
          chmod +x ./scripts/deploy.sh
          ./scripts/deploy.sh
        shell: bash